In [1]:
import pandas as pd
from rdkit import Chem
from chembl_webresource_client.new_client import new_client
from rdkit.Chem import PandasTools
from IPython.display import HTML

C:\Users\ovtti\anaconda3\Lib\site-packages\chembl_webresource_client\__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

# Search for Target protein

In [2]:
activity = new_client.activity
res = activity.filter(target_chembl_id='CHEMBL3192').filter(standard_type="IC50")

In [3]:
df = pd.DataFrame.from_dict(res)

In [4]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1266085,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,100.0
1,None,None,1266090,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,100.0
2,None,None,1270391,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,0.8
3,None,None,1271622,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,0.69
4,None,None,1275487,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,6.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4747,None,1234589,28878071,[],CHEMBL5738809,Enzymatic Assay: The IC50 values for aforement...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,1420.0
4748,None,1234593,28878083,[],CHEMBL5738809,Enzymatic Assay: The IC50 values for aforement...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,979.0
4749,None,1234597,28878095,[],CHEMBL5738809,Enzymatic Assay: The IC50 values for aforement...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,175.0
4750,None,1234619,28878125,[],CHEMBL5738819,Electrophoretic Mobility Shift Assay: Activity...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,1000.0
4751,None,1234630,28878158,[],CHEMBL5738819,Electrophoretic Mobility Shift Assay: Activity...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,1000.0

In [5]:
df.columns

Index(['action_type', 'activity_comment', 'activity_id', 'activity_properties',
       'assay_chembl_id', 'assay_description', 'assay_type',
       'assay_variant_accession', 'assay_variant_mutation', 'bao_endpoint',
       'bao_format', 'bao_label', 'canonical_smiles', 'data_validity_comment',
       'data_validity_description', 'document_chembl_id', 'document_journal',
       'document_year', 'ligand_efficiency', 'molecule_chembl_id',
       'molecule_pref_name', 'parent_molecule_chembl_id', 'pchembl_value',
       'potential_duplicate', 'qudt_units', 'record_id', 'relation', 'src_id',
       'standard_flag', 'standard_relation', 'standard_text_value',
       'standard_type', 'standard_units', 'standard_upper_value',
       'standard_value', 'target_chembl_id', 'target_organism',
       'target_pref_name', 'target_tax_id', 'text_value', 'toid', 'type',
       'units', 'uo_units', 'upper_value', 'value'],
      dtype='object')

# Handling data

If any compounds has missing value for the standard_value and canonical_smiles columns then drop its.

In [6]:
df_nan_column = df[df['canonical_smiles'].isna()]
df_nan_column

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
1598,None,381771,17755317,[],CHEMBL3888199,HDAC Activity Assay: HDAC assay is performed u...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,417.0
1599,None,381772,17755318,[],CHEMBL3888199,HDAC Activity Assay: HDAC assay is performed u...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,397.0
1600,None,381773,17755319,[],CHEMBL3888199,HDAC Activity Assay: HDAC assay is performed u...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,911.0
1601,None,381774,17755320,[],CHEMBL3888199,HDAC Activity Assay: HDAC assay is performed u...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,324.0
1602,None,381775,17755321,[],CHEMBL3888199,HDAC Activity Assay: HDAC assay is performed u...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,422.0
1603,None,381776,17755322,[],CHEMBL3888199,HDAC Activity Assay: HDAC assay is performed u...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,174.0

In [7]:
df2 = df[df.pchembl_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

C:\Users\ovtti\AppData\Local\Temp\ipykernel_12240\1951196501.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
2,None,None,1270391,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,0.8
3,None,None,1271622,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,0.69
4,None,None,1275487,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,6.8
5,None,None,1275492,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,0.78
6,None,None,1276796,[],CHEMBL695893,Inhibition of Histone deacetylase 8 (HDAC8) of...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,uM,UO_0000065,None,9.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4745,None,1234581,28878047,[],CHEMBL5738809,Enzymatic Assay: The IC50 values for aforement...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,428.0
4746,None,1234585,28878059,[],CHEMBL5738809,Enzymatic Assay: The IC50 values for aforement...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,3060.0
4747,None,1234589,28878071,[],CHEMBL5738809,Enzymatic Assay: The IC50 values for aforement...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,1420.0
4748,None,1234593,28878083,[],CHEMBL5738809,Enzymatic Assay: The IC50 values for aforement...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,979.0
4749,None,1234597,28878095,[],CHEMBL5738809,Enzymatic Assay: The IC50 values for aforement...,B,None,None,BAO_0000190,...,Homo sapiens,Histone deacetylase 8,9606,None,None,IC50,nM,UO_0000065,None,175.0

In [9]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value','pchembl_value', 'document_chembl_id']

In [10]:
df3 = df2[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value,pchembl_value,document_chembl_id
2,CHEMBL336935,O=CN(O)CCCCCC(C(=O)Nc1ccc2ncccc2c1)C(=O)Nc1ccc...,800.0,6.10,CHEMBL1137945
3,CHEMBL140525,O=CN(O)CCCCCC(C(=O)Nc1cnc2ccccc2c1)C(=O)Nc1cnc...,690.0,6.16,CHEMBL1137945
4,CHEMBL141082,O=CN(O)CCCCCC(=O)Nc1ccccc1,6800.0,5.17,CHEMBL1137945
5,CHEMBL141909,O=CN(O)CCCCCCCC(=O)Nc1ccc2ccccc2c1,780.0,6.11,CHEMBL1137945
6,CHEMBL141885,O=CN(O)CCCCCNC(=O)CCc1ccccc1,9700.0,5.01,CHEMBL1137945
...,...,...,...,...,...
4745,CHEMBL4442777,O=C(NO)c1ccc(Cn2c(=O)n(CCc3cccc(F)c3)c(=O)c3cc...,428.0,6.37,CHEMBL5729500
4746,CHEMBL4474286,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccccc3)c(=O)c3ccc(C...,3060.0,5.51,CHEMBL5729500
4747,CHEMBL5891478,CNc1ccc(CCn2c(=O)c3ccccc3n(Cc3ccc(C(=O)NO)cc3)...,1420.0,5.85,CHEMBL5729500
4748,CHEMBL5770781,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccc(N4CCOCC4)cc3)c(...,979.0,6.01,CHEMBL5729500
4749,CHEMBL99,CC(/C=C/C(=O)NO)=C\[C@@H](C)C(=O)c1ccc(N(C)C)cc1,175.0,6.76,CHEMBL5729500

In [11]:
def convert_smi_to_inchi(smi):
    molecule = Chem.MolFromSmiles(smi)
    inchikey = str(Chem.MolToInchi(molecule))
    return inchikey

In [12]:
df3["inchi"] = df3.apply(lambda x: convert_smi_to_inchi(x.canonical_smiles), axis=1)

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged; Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged; Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Omitted undefined stereo

[07:15:13] WARNING: Charges were rearranged

[07:15:13] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged; Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Charges were rearranged; Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Proton(s) added/removed

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Charges were rearranged; Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged; Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Proton(s) added/removed

[07:15:14] WARNING: Proton(s) added/removed

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Proton(s) added/removed

[07:15:14] WARNING: Charges were rearranged; Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Charges were rearranged

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo

[07:15:14] WARNING: Omitted undefined stereo


In [13]:
df3

,molecule_chembl_id,canonical_smiles,standard_value,pchembl_value,document_chembl_id,inchi
2,CHEMBL336935,O=CN(O)CCCCCC(C(=O)Nc1ccc2ncccc2c1)C(=O)Nc1ccc...,800.0,6.10,CHEMBL1137945,InChI=1S/C27H27N5O4/c33-18-32(36)15-3-1-2-8-23...
3,CHEMBL140525,O=CN(O)CCCCCC(C(=O)Nc1cnc2ccccc2c1)C(=O)Nc1cnc...,690.0,6.16,CHEMBL1137945,InChI=1S/C27H27N5O4/c33-18-32(36)13-7-1-2-10-2...
4,CHEMBL141082,O=CN(O)CCCCCC(=O)Nc1ccccc1,6800.0,5.17,CHEMBL1137945,InChI=1S/C13H18N2O3/c16-11-15(18)10-6-2-5-9-13...
5,CHEMBL141909,O=CN(O)CCCCCCCC(=O)Nc1ccc2ccccc2c1,780.0,6.11,CHEMBL1137945,InChI=1S/C19H24N2O3/c22-15-21(24)13-7-3-1-2-4-...
6,CHEMBL141885,O=CN(O)CCCCCNC(=O)CCc1ccccc1,9700.0,5.01,CHEMBL1137945,InChI=1S/C15H22N2O3/c18-13-17(20)12-6-2-5-11-1...
...,...,...,...,...,...,...
4745,CHEMBL4442777,O=C(NO)c1ccc(Cn2c(=O)n(CCc3cccc(F)c3)c(=O)c3cc...,428.0,6.37,CHEMBL5729500,InChI=1S/C24H20FN3O4/c25-19-5-3-4-16(14-19)12-...
4746,CHEMBL4474286,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccccc3)c(=O)c3ccc(C...,3060.0,5.51,CHEMBL5729500,InChI=1S/C27H25N3O4/c31-25(28-34)21-8-6-19(7-9...
4747,CHEMBL5891478,CNc1ccc(CCn2c(=O)c3ccccc3n(Cc3ccc(C(=O)NO)cc3)...,1420.0,5.85,CHEMBL5729500,InChI=1S/C25H24N4O4/c1-26-20-12-8-17(9-13-20)1...
4748,CHEMBL5770781,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccc(N4CCOCC4)cc3)c(...,979.0,6.01,CHEMBL5729500,InChI=1S/C28H28N4O5/c33-26(29-36)22-9-5-21(6-1...
4749,CHEMBL99,CC(/C=C/C(=O)NO)=C\[C@@H](C)C(=O)c1ccc(N(C)C)cc1,175.0,6.76,CHEMBL5729500,InChI=1S/C17H22N2O3/c1-12(5-10-16(20)18-22)11-...

In [14]:
df3['pchembl_value'] = pd.to_numeric(df3['pchembl_value'], downcast="float")

C:\Users\ovtti\AppData\Local\Temp\ipykernel_7452\3332614481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['pchembl_value'] = pd.to_numeric(df3['pchembl_value'], downcast="float")

In [14]:
df3['pchembl_value'] = pd.to_numeric(df3['pchembl_value'], downcast="float")

C:\Users\ovtti\AppData\Local\Temp\ipykernel_12240\3332614481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['pchembl_value'] = pd.to_numeric(df3['pchembl_value'], downcast="float")

In [15]:
mean_std = df3.groupby(['canonical_smiles'], as_index=False).agg({'pchembl_value':['mean','std']})
mean_std

                                       canonical_smiles pchembl_value
                                                                 mean  std
0                                             Brc1cncs1          5.25  NaN
1       C#CCN(C)CCCOc1cc(NC(=O)CCCCCCC(=O)NO)c(Cl)cc1Cl          5.75  NaN
2           C#CCN(C)CCCOc1cc(NC(=O)CCCCCCC(=O)NO)ccc1Cl          7.30  NaN
3          C#CCN(C)CCCOc1cc(NC(=O)CCCCCCCC(=O)NO)ccc1Cl          5.95  NaN
4         C#CCN(C)CCCOc1cc(NC(=O)CCCCCCCCC(=O)NO)ccc1Cl          5.61  NaN
...                                                 ...           ...  ...
2891  [N-]=[N+]=NCc1cc(N=[N+]=[N-])cc(C(=O)Nc2ccc(-c...          6.19  0.0
2892  [N-]=[N+]=NCc1cc(N=[N+]=[N-])cc(C(=O)Nc2ccc(Cn...          6.31  NaN
2893  [N-]=[N+]=Nc1ccc(-c2cc(C(=O)NCCCCCCC(=O)NO)no2...          6.15  NaN
2894  [N-]=[N+]=Nc1ccc(-c2csc(NC(=O)CCCCCCC(=O)NO)n2...          5.57  NaN
2895  [N-]=[N+]=Nc1ccc(Cn2cc(NC(=O)CCCCCCC(=O)NO)cn2...          7.55  NaN

[2896 rows x 3 columns]

In [16]:
# Fix the column names while preserving 'canonical_smiles'
new_columns = []
for col in mean_std.columns:
    if isinstance(col, tuple):
        if col[0] == 'canonical_smiles':
            new_columns.append('canonical_smiles')  # Keep the original name
        else:
            new_columns.append(f'{col[0]}_{col[1]}')
    else:
        new_columns.append(col)

mean_std.columns = new_columns

In [17]:
mean_std

,canonical_smiles,pchembl_value_mean,pchembl_value_std
0,Brc1cncs1,5.25,NaN
1,C#CCN(C)CCCOc1cc(NC(=O)CCCCCCC(=O)NO)c(Cl)cc1Cl,5.75,NaN
2,C#CCN(C)CCCOc1cc(NC(=O)CCCCCCC(=O)NO)ccc1Cl,7.30,NaN
3,C#CCN(C)CCCOc1cc(NC(=O)CCCCCCCC(=O)NO)ccc1Cl,5.95,NaN
4,C#CCN(C)CCCOc1cc(NC(=O)CCCCCCCCC(=O)NO)ccc1Cl,5.61,NaN
...,...,...,...
2891,[N-]=[N+]=NCc1cc(N=[N+]=[N-])cc(C(=O)Nc2ccc(-c...,6.19,0.0
2892,[N-]=[N+]=NCc1cc(N=[N+]=[N-])cc(C(=O)Nc2ccc(Cn...,6.31,NaN
2893,[N-]=[N+]=Nc1ccc(-c2cc(C(=O)NCCCCCCC(=O)NO)no2...,6.15,NaN
2894,[N-]=[N+]=Nc1ccc(-c2csc(NC(=O)CCCCCCC(=O)NO)n2...,5.57,NaN
2895,[N-]=[N+]=Nc1ccc(Cn2cc(NC(=O)CCCCCCC(=O)NO)cn2...,7.55,NaN

In [18]:
df4 = df3.merge(mean_std, on=['canonical_smiles'])

In [19]:
df4

,molecule_chembl_id,canonical_smiles,standard_value,pchembl_value,document_chembl_id,inchi,pchembl_value_mean,pchembl_value_std
0,CHEMBL336935,O=CN(O)CCCCCC(C(=O)Nc1ccc2ncccc2c1)C(=O)Nc1ccc...,800.0,6.10,CHEMBL1137945,InChI=1S/C27H27N5O4/c33-18-32(36)15-3-1-2-8-23...,6.10000,NaN
1,CHEMBL140525,O=CN(O)CCCCCC(C(=O)Nc1cnc2ccccc2c1)C(=O)Nc1cnc...,690.0,6.16,CHEMBL1137945,InChI=1S/C27H27N5O4/c33-18-32(36)13-7-1-2-10-2...,6.16000,NaN
2,CHEMBL141082,O=CN(O)CCCCCC(=O)Nc1ccccc1,6800.0,5.17,CHEMBL1137945,InChI=1S/C13H18N2O3/c16-11-15(18)10-6-2-5-9-13...,5.17000,NaN
3,CHEMBL141909,O=CN(O)CCCCCCCC(=O)Nc1ccc2ccccc2c1,780.0,6.11,CHEMBL1137945,InChI=1S/C19H24N2O3/c22-15-21(24)13-7-3-1-2-4-...,6.11000,NaN
4,CHEMBL141885,O=CN(O)CCCCCNC(=O)CCc1ccccc1,9700.0,5.01,CHEMBL1137945,InChI=1S/C15H22N2O3/c18-13-17(20)12-6-2-5-11-1...,5.01000,NaN
...,...,...,...,...,...,...,...,...
3648,CHEMBL4442777,O=C(NO)c1ccc(Cn2c(=O)n(CCc3cccc(F)c3)c(=O)c3cc...,428.0,6.37,CHEMBL5729500,InChI=1S/C24H20FN3O4/c25-19-5-3-4-16(14-19)12-...,6.37000,0.000000
3649,CHEMBL4474286,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccccc3)c(=O)c3ccc(C...,3060.0,5.51,CHEMBL5729500,InChI=1S/C27H25N3O4/c31-25(28-34)21-8-6-19(7-9...,5.51000,0.000000
3650,CHEMBL5891478,CNc1ccc(CCn2c(=O)c3ccccc3n(Cc3ccc(C(=O)NO)cc3)...,1420.0,5.85,CHEMBL5729500,InChI=1S/C25H24N4O4/c1-26-20-12-8-17(9-13-20)1...,5.85000,NaN
3651,CHEMBL5770781,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccc(N4CCOCC4)cc3)c(...,979.0,6.01,CHEMBL5729500,InChI=1S/C28H28N4O5/c33-26(29-36)22-9-5-21(6-1...,6.01000,NaN
3652,CHEMBL99,CC(/C=C/C(=O)NO)=C\[C@@H](C)C(=O)c1ccc(N(C)C)cc1,175.0,6.76,CHEMBL5729500,InChI=1S/C17H22N2O3/c1-12(5-10-16(20)18-22)11-...,6.38963,0.519448

In [20]:
df4['pchembl_value_std'] = df4['pchembl_value_std']. fillna (0)

In [21]:
df2_nr = df4.drop_duplicates(subset='canonical_smiles', keep='first')
df2_nr

,molecule_chembl_id,canonical_smiles,standard_value,pchembl_value,document_chembl_id,inchi,pchembl_value_mean,pchembl_value_std
0,CHEMBL336935,O=CN(O)CCCCCC(C(=O)Nc1ccc2ncccc2c1)C(=O)Nc1ccc...,800.0,6.10,CHEMBL1137945,InChI=1S/C27H27N5O4/c33-18-32(36)15-3-1-2-8-23...,6.10,0.0
1,CHEMBL140525,O=CN(O)CCCCCC(C(=O)Nc1cnc2ccccc2c1)C(=O)Nc1cnc...,690.0,6.16,CHEMBL1137945,InChI=1S/C27H27N5O4/c33-18-32(36)13-7-1-2-10-2...,6.16,0.0
2,CHEMBL141082,O=CN(O)CCCCCC(=O)Nc1ccccc1,6800.0,5.17,CHEMBL1137945,InChI=1S/C13H18N2O3/c16-11-15(18)10-6-2-5-9-13...,5.17,0.0
3,CHEMBL141909,O=CN(O)CCCCCCCC(=O)Nc1ccc2ccccc2c1,780.0,6.11,CHEMBL1137945,InChI=1S/C19H24N2O3/c22-15-21(24)13-7-3-1-2-4-...,6.11,0.0
4,CHEMBL141885,O=CN(O)CCCCCNC(=O)CCc1ccccc1,9700.0,5.01,CHEMBL1137945,InChI=1S/C15H22N2O3/c18-13-17(20)12-6-2-5-11-1...,5.01,0.0
...,...,...,...,...,...,...,...,...
3635,CHEMBL5822037,Cn1c(=O)c2ccc(Cl)cc2n(Cc2ccc(C(=O)NO)cc2)c1=O,523.0,6.28,CHEMBL5729500,InChI=1S/C17H14ClN3O4/c1-20-16(23)13-7-6-12(18...,6.28,0.0
3636,CHEMBL5968609,O=C(NO)c1ccc(Cn2c(=O)n(Cc3ccccc3)c(=O)c3ccccc3...,486.0,6.31,CHEMBL5729500,InChI=1S/C23H19N3O4/c27-21(24-30)18-12-10-17(1...,6.31,0.0
3646,CHEMBL5759520,O=C(NO)c1ccc(Cn2c(=O)n(CCc3cccs3)c(=O)c3ccccc3...,287.0,6.54,CHEMBL5729500,InChI=1S/C22H19N3O4S/c26-20(23-29)16-9-7-15(8-...,6.54,0.0
3650,CHEMBL5891478,CNc1ccc(CCn2c(=O)c3ccccc3n(Cc3ccc(C(=O)NO)cc3)...,1420.0,5.85,CHEMBL5729500,InChI=1S/C25H24N4O4/c1-26-20-12-8-17(9-13-20)1...,5.85,0.0
3651,CHEMBL5770781,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccc(N4CCOCC4)cc3)c(...,979.0,6.01,CHEMBL5729500,InChI=1S/C28H28N4O5/c33-26(29-36)22-9-5-21(6-1...,6.01,0.0

In [22]:
df2_nr

,molecule_chembl_id,canonical_smiles,standard_value,pchembl_value,document_chembl_id,inchi,pchembl_value_mean,pchembl_value_std
0,CHEMBL336935,O=CN(O)CCCCCC(C(=O)Nc1ccc2ncccc2c1)C(=O)Nc1ccc...,800.0,6.10,CHEMBL1137945,InChI=1S/C27H27N5O4/c33-18-32(36)15-3-1-2-8-23...,6.10,0.0
1,CHEMBL140525,O=CN(O)CCCCCC(C(=O)Nc1cnc2ccccc2c1)C(=O)Nc1cnc...,690.0,6.16,CHEMBL1137945,InChI=1S/C27H27N5O4/c33-18-32(36)13-7-1-2-10-2...,6.16,0.0
2,CHEMBL141082,O=CN(O)CCCCCC(=O)Nc1ccccc1,6800.0,5.17,CHEMBL1137945,InChI=1S/C13H18N2O3/c16-11-15(18)10-6-2-5-9-13...,5.17,0.0
3,CHEMBL141909,O=CN(O)CCCCCCCC(=O)Nc1ccc2ccccc2c1,780.0,6.11,CHEMBL1137945,InChI=1S/C19H24N2O3/c22-15-21(24)13-7-3-1-2-4-...,6.11,0.0
4,CHEMBL141885,O=CN(O)CCCCCNC(=O)CCc1ccccc1,9700.0,5.01,CHEMBL1137945,InChI=1S/C15H22N2O3/c18-13-17(20)12-6-2-5-11-1...,5.01,0.0
...,...,...,...,...,...,...,...,...
3635,CHEMBL5822037,Cn1c(=O)c2ccc(Cl)cc2n(Cc2ccc(C(=O)NO)cc2)c1=O,523.0,6.28,CHEMBL5729500,InChI=1S/C17H14ClN3O4/c1-20-16(23)13-7-6-12(18...,6.28,0.0
3636,CHEMBL5968609,O=C(NO)c1ccc(Cn2c(=O)n(Cc3ccccc3)c(=O)c3ccccc3...,486.0,6.31,CHEMBL5729500,InChI=1S/C23H19N3O4/c27-21(24-30)18-12-10-17(1...,6.31,0.0
3646,CHEMBL5759520,O=C(NO)c1ccc(Cn2c(=O)n(CCc3cccs3)c(=O)c3ccccc3...,287.0,6.54,CHEMBL5729500,InChI=1S/C22H19N3O4S/c26-20(23-29)16-9-7-15(8-...,6.54,0.0
3650,CHEMBL5891478,CNc1ccc(CCn2c(=O)c3ccccc3n(Cc3ccc(C(=O)NO)cc3)...,1420.0,5.85,CHEMBL5729500,InChI=1S/C25H24N4O4/c1-26-20-12-8-17(9-13-20)1...,5.85,0.0
3651,CHEMBL5770781,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccc(N4CCOCC4)cc3)c(...,979.0,6.01,CHEMBL5729500,InChI=1S/C28H28N4O5/c33-26(29-36)22-9-5-21(6-1...,6.01,0.0

In [23]:
selection = ['molecule_chembl_id','canonical_smiles','pchembl_value_mean', 'pchembl_value_std', 'inchi']

In [24]:
df5=df2_nr[selection]
df5

,molecule_chembl_id,canonical_smiles,pchembl_value_mean,pchembl_value_std,inchi
0,CHEMBL336935,O=CN(O)CCCCCC(C(=O)Nc1ccc2ncccc2c1)C(=O)Nc1ccc...,6.10,0.0,InChI=1S/C27H27N5O4/c33-18-32(36)15-3-1-2-8-23...
1,CHEMBL140525,O=CN(O)CCCCCC(C(=O)Nc1cnc2ccccc2c1)C(=O)Nc1cnc...,6.16,0.0,InChI=1S/C27H27N5O4/c33-18-32(36)13-7-1-2-10-2...
2,CHEMBL141082,O=CN(O)CCCCCC(=O)Nc1ccccc1,5.17,0.0,InChI=1S/C13H18N2O3/c16-11-15(18)10-6-2-5-9-13...
3,CHEMBL141909,O=CN(O)CCCCCCCC(=O)Nc1ccc2ccccc2c1,6.11,0.0,InChI=1S/C19H24N2O3/c22-15-21(24)13-7-3-1-2-4-...
4,CHEMBL141885,O=CN(O)CCCCCNC(=O)CCc1ccccc1,5.01,0.0,InChI=1S/C15H22N2O3/c18-13-17(20)12-6-2-5-11-1...
...,...,...,...,...,...
3635,CHEMBL5822037,Cn1c(=O)c2ccc(Cl)cc2n(Cc2ccc(C(=O)NO)cc2)c1=O,6.28,0.0,InChI=1S/C17H14ClN3O4/c1-20-16(23)13-7-6-12(18...
3636,CHEMBL5968609,O=C(NO)c1ccc(Cn2c(=O)n(Cc3ccccc3)c(=O)c3ccccc3...,6.31,0.0,InChI=1S/C23H19N3O4/c27-21(24-30)18-12-10-17(1...
3646,CHEMBL5759520,O=C(NO)c1ccc(Cn2c(=O)n(CCc3cccs3)c(=O)c3ccccc3...,6.54,0.0,InChI=1S/C22H19N3O4S/c26-20(23-29)16-9-7-15(8-...
3650,CHEMBL5891478,CNc1ccc(CCn2c(=O)c3ccccc3n(Cc3ccc(C(=O)NO)cc3)...,5.85,0.0,InChI=1S/C25H24N4O4/c1-26-20-12-8-17(9-13-20)1...
3651,CHEMBL5770781,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccc(N4CCOCC4)cc3)c(...,6.01,0.0,InChI=1S/C28H28N4O5/c33-26(29-36)22-9-5-21(6-1...

In [25]:
def remove_salt(smi):
    if '.' in smi:
        smi='SALT_MIX'
    
    return smi

In [26]:
df5["canonical_smiles"] = df5.apply(lambda x: remove_salt(x.canonical_smiles), axis=1)

C:\Users\ovtti\AppData\Local\Temp\ipykernel_12240\3359572543.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["canonical_smiles"] = df5.apply(lambda x: remove_salt(x.canonical_smiles), axis=1)

In [27]:
df6 = df5[(df5[('canonical_smiles')] != 'SALT_MIX')]

In [28]:
df6

,molecule_chembl_id,canonical_smiles,pchembl_value_mean,pchembl_value_std,inchi
0,CHEMBL336935,O=CN(O)CCCCCC(C(=O)Nc1ccc2ncccc2c1)C(=O)Nc1ccc...,6.10,0.0,InChI=1S/C27H27N5O4/c33-18-32(36)15-3-1-2-8-23...
1,CHEMBL140525,O=CN(O)CCCCCC(C(=O)Nc1cnc2ccccc2c1)C(=O)Nc1cnc...,6.16,0.0,InChI=1S/C27H27N5O4/c33-18-32(36)13-7-1-2-10-2...
2,CHEMBL141082,O=CN(O)CCCCCC(=O)Nc1ccccc1,5.17,0.0,InChI=1S/C13H18N2O3/c16-11-15(18)10-6-2-5-9-13...
3,CHEMBL141909,O=CN(O)CCCCCCCC(=O)Nc1ccc2ccccc2c1,6.11,0.0,InChI=1S/C19H24N2O3/c22-15-21(24)13-7-3-1-2-4-...
4,CHEMBL141885,O=CN(O)CCCCCNC(=O)CCc1ccccc1,5.01,0.0,InChI=1S/C15H22N2O3/c18-13-17(20)12-6-2-5-11-1...
...,...,...,...,...,...
3635,CHEMBL5822037,Cn1c(=O)c2ccc(Cl)cc2n(Cc2ccc(C(=O)NO)cc2)c1=O,6.28,0.0,InChI=1S/C17H14ClN3O4/c1-20-16(23)13-7-6-12(18...
3636,CHEMBL5968609,O=C(NO)c1ccc(Cn2c(=O)n(Cc3ccccc3)c(=O)c3ccccc3...,6.31,0.0,InChI=1S/C23H19N3O4/c27-21(24-30)18-12-10-17(1...
3646,CHEMBL5759520,O=C(NO)c1ccc(Cn2c(=O)n(CCc3cccs3)c(=O)c3ccccc3...,6.54,0.0,InChI=1S/C22H19N3O4S/c26-20(23-29)16-9-7-15(8-...
3650,CHEMBL5891478,CNc1ccc(CCn2c(=O)c3ccccc3n(Cc3ccc(C(=O)NO)cc3)...,5.85,0.0,InChI=1S/C25H24N4O4/c1-26-20-12-8-17(9-13-20)1...
3651,CHEMBL5770781,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccc(N4CCOCC4)cc3)c(...,6.01,0.0,InChI=1S/C28H28N4O5/c33-26(29-36)22-9-5-21(6-1...

# Save to csv

In [34]:
df6.to_csv('HDAC8_exp_data_inchi.csv', sep=",", index=False)

# Processing for QSAR

In [30]:
#keep only SD less thab 0.5 SD
df6 = df6[(df6['pchembl_value_std'] < 0.5)]
df6

,molecule_chembl_id,canonical_smiles,pchembl_value_mean,pchembl_value_std,inchi
0,CHEMBL336935,O=CN(O)CCCCCC(C(=O)Nc1ccc2ncccc2c1)C(=O)Nc1ccc...,6.10,0.0,InChI=1S/C27H27N5O4/c33-18-32(36)15-3-1-2-8-23...
1,CHEMBL140525,O=CN(O)CCCCCC(C(=O)Nc1cnc2ccccc2c1)C(=O)Nc1cnc...,6.16,0.0,InChI=1S/C27H27N5O4/c33-18-32(36)13-7-1-2-10-2...
2,CHEMBL141082,O=CN(O)CCCCCC(=O)Nc1ccccc1,5.17,0.0,InChI=1S/C13H18N2O3/c16-11-15(18)10-6-2-5-9-13...
3,CHEMBL141909,O=CN(O)CCCCCCCC(=O)Nc1ccc2ccccc2c1,6.11,0.0,InChI=1S/C19H24N2O3/c22-15-21(24)13-7-3-1-2-4-...
4,CHEMBL141885,O=CN(O)CCCCCNC(=O)CCc1ccccc1,5.01,0.0,InChI=1S/C15H22N2O3/c18-13-17(20)12-6-2-5-11-1...
...,...,...,...,...,...
3635,CHEMBL5822037,Cn1c(=O)c2ccc(Cl)cc2n(Cc2ccc(C(=O)NO)cc2)c1=O,6.28,0.0,InChI=1S/C17H14ClN3O4/c1-20-16(23)13-7-6-12(18...
3636,CHEMBL5968609,O=C(NO)c1ccc(Cn2c(=O)n(Cc3ccccc3)c(=O)c3ccccc3...,6.31,0.0,InChI=1S/C23H19N3O4/c27-21(24-30)18-12-10-17(1...
3646,CHEMBL5759520,O=C(NO)c1ccc(Cn2c(=O)n(CCc3cccs3)c(=O)c3ccccc3...,6.54,0.0,InChI=1S/C22H19N3O4S/c26-20(23-29)16-9-7-15(8-...
3650,CHEMBL5891478,CNc1ccc(CCn2c(=O)c3ccccc3n(Cc3ccc(C(=O)NO)cc3)...,5.85,0.0,InChI=1S/C25H24N4O4/c1-26-20-12-8-17(9-13-20)1...
3651,CHEMBL5770781,O=C(NO)c1ccc(Cn2c(=O)n(CCc3ccc(N4CCOCC4)cc3)c(...,6.01,0.0,InChI=1S/C28H28N4O5/c33-26(29-36)22-9-5-21(6-1...

In [52]:
df6.sort_values(by='pchembl_value_std')

,molecule_chembl_id,canonical_smiles,pchembl_value_mean,pchembl_value_std,inchi
0,CHEMBL336935,O=CN(O)CCCCCC(C(=O)Nc1ccc2ncccc2c1)C(=O)Nc1ccc...,6.100,0.000000,InChI=1S/C27H27N5O4/c33-18-32(36)15-3-1-2-8-23...
2357,CHEMBL5192326,COc1cc(C(=O)c2csc(-c3ccc(/C=C/C(=O)NO)cc3)n2)c...,5.570,0.000000,InChI=1S/C22H20N2O6S/c1-28-17-10-15(11-18(29-2...
2360,CHEMBL5171489,C#CCN(C)Cc1cccc(NC(=O)CCCCCCC(=O)NO)c1,6.680,0.000000,InChI=1S/C19H27N3O3/c1-3-13-22(2)15-16-9-8-10-...
2361,CHEMBL5209294,C#Cc1nc(C(=O)NCCCCCCC(=O)NO)cs1,6.500,0.000000,InChI=1S/C13H17N3O3S/c1-2-12-15-10(9-20-12)13(...
2362,CHEMBL5181798,C#Cc1nc(/C=C\CCCCCC(=O)NO)cs1,6.330,0.000000,InChI=1S/C13H16N2O2S/c1-2-13-14-11(10-18-13)8-...
...,...,...,...,...,...
498,CHEMBL556332,O=C(/C=C/c1ccc(-c2ccc(O)cc2)cc1)NO,6.510,0.395980,InChI=1S/C15H13NO3/c17-14-8-6-13(7-9-14)12-4-1...
935,CHEMBL343448,C/C=C1\NC(=O)[C@H]2CSSCC/C=C/[C@H](CC(=O)N[C@H...,7.700,0.424264,InChI=1S/C24H36N4O6S2/c1-6-16-21(30)28-20(14(4...
1877,CHEMBL4640205,O=C(NO)c1ccc(N(Cc2ccccc2)C(=O)c2cccc(C(F)(F)F)...,6.900,0.452548,"InChI=1S/C22H17F3N2O3/c23-22(24,25)18-8-4-7-17..."
1884,CHEMBL4642821,CC(C)N(C(=O)c1cc(C(F)(F)F)cc(C(F)(F)F)c1)c1ccc...,7.290,0.480833,InChI=1S/C19H16F6N2O3/c1-10(2)27(15-5-3-11(4-6...
1158,CHEMBL3800394,COc1ccc(C(=O)NO)cc1NC(=O)c1ccc(-c2ccccc2)cc1,7.235,0.487904,InChI=1S/C21H18N2O4/c1-27-19-12-11-17(21(25)23...

In [53]:
data=df6.drop(['pchembl_value_std' ], axis=1)

In [54]:
data.describe()

       pchembl_value_mean
count         2763.000000
mean             6.022283
std              0.851741
min              4.010000
25%              5.460000
50%              5.970000
75%              6.580000
max              9.920000

# Creating training and test samples

In [55]:
data=data.sort_values(by='pchembl_value_mean')
data

,molecule_chembl_id,canonical_smiles,pchembl_value_mean,inchi
2835,CHEMBL5429446,Nc1ccccc1NC(=O)c1ccc(NC(=O)Cc2cccc3ccccc23)cn1,4.01,InChI=1S/C24H20N4O2/c25-20-10-3-4-11-21(20)28-...
325,CHEMBL1767046,CNC(=O)/C(CCCCC[C@H](NCc1ccc(OC)cc1)C(=O)Nc1cc...,4.02,InChI=1S/C24H32N4O4/c1-25-23(29)22(28-31)12-8-...
316,CHEMBL1469,O=C(O)CCCc1ccccc1,4.03,InChI=1S/C10H12O2/c11-10(12)8-4-7-9-5-2-1-3-6-...
908,CHEMBL3605493,Nc1ccccc1NC(=O)c1ccc(CSC2=N[C@@H](Cc3ccccc3)CO...,4.06,InChI=1S/C24H23N3O2S/c25-21-8-4-5-9-22(21)27-2...
906,CHEMBL3605494,Nc1ccccc1NC(=O)c1ccc(CNC2=N[C@@H](c3ccccc3)CO2...,4.06,InChI=1S/C23H22N4O2/c24-19-8-4-5-9-20(19)26-22...
...,...,...,...,...
2996,CHEMBL5632276,O=C(NO)[C@@H](Cc1ccccc1)n1nnc(-c2ccccc2)c1C#CC...,9.10,InChI=1S/C22H20N4O2/c27-22(24-28)20(15-17-7-3-...
1787,CHEMBL4534486,O=C(NO)[C@H](Cc1ccccc1)n1nnc(-c2ccccc2)c1C#CC1CC1,9.10,InChI=1S/C22H20N4O2/c27-22(24-28)20(15-17-7-3-...
1629,CHEMBL4441774,CC(C)[C@@H]1NC(=O)[C@]2(C)CSC(=N2)c2csc(n2)CNC...,9.39,InChI=1S/C21H27FN4O4S3/c1-11(2)17-19(28)30-13(...
3004,CHEMBL98245,O=C(/C=C/C#Cc1cccc(NS(=O)(=O)c2ccccc2)c1)NO,9.43,InChI=1S/C17H14N2O4S/c20-17(18-21)12-5-4-7-14-...
2943,CHEMBL5595114,COc1cc(/C=C2/C(=O)NCC(=O)N2C)ccc1/C=C/C(=O)NO,9.92,InChI=1S/C16H17N3O5/c1-19-12(16(22)17-9-15(19)...

In [56]:
data_test=data.loc[::5]
data_test.head(20)

,molecule_chembl_id,canonical_smiles,pchembl_value_mean,inchi
2835,CHEMBL5429446,Nc1ccccc1NC(=O)c1ccc(NC(=O)Cc2cccc3ccccc23)cn1,4.01,InChI=1S/C24H20N4O2/c25-20-10-3-4-11-21(20)28-...
326,CHEMBL1767047,CNC(=O)/C(CCCCC[C@@H](C(=O)Nc1ccccc1)N(Cc1cccc...,4.06,InChI=1S/C30H36N4O3/c1-31-29(35)27(33-37)20-12...
2832,CHEMBL5419832,Nc1ccccc1NC(=O)c1ccc(NC(=O)Cc2ccccc2)cn1,4.11,InChI=1S/C20H18N4O2/c21-16-8-4-5-9-17(16)24-20...
139,CHEMBL564916,Nc1ccccc1NC(=O)CCCCCC(c1c[nH]c2ccccc12)c1c[nH]...,4.13,InChI=1S/C29H30N4O/c30-25-13-6-9-16-28(25)33-2...
910,CHEMBL3605501,Nc1ccccc1NC(=O)c1ccc(CNC2=N[C@@H](Cc3ccccc3)CO...,4.20,InChI=1S/C24H24N4O2/c25-21-8-4-5-9-22(21)28-23...
915,CHEMBL3605504,Nc1ccccc1NC(=O)c1ccc(CNC2=NC(c3ccccc3)(c3ccccc...,4.27,InChI=1S/C29H26N4O2/c30-25-13-7-8-14-26(25)32-...
2613,CHEMBL5266902,COc1ccc(NC(=O)CCCCCCNC(=O)C(O)(O)C(F)(F)F)cc1,4.29,InChI=1S/C17H23F3N2O5/c1-27-13-9-7-12(8-10-13)...
3460,CHEMBL5888369,Fc1ccc2ccc(OCc3ccc(-c4noc(C(F)(F)F)n4)cn3)nc2c1,4.35,InChI=1S/C18H10F4N4O2/c19-12-4-1-10-3-6-15(24-...
3453,CHEMBL5935148,CC1(C)CC(c2ccccc2)N(c2ccc(-c3noc(C(F)(F)F)n3)c...,4.35,InChI=1S/C21H17F4N3O2/c1-20(2)11-16(12-6-4-3-5...
3394,CHEMBL5782142,Fc1cc(COc2ccccc2)ccc1-c1noc(C(F)(F)F)n1,4.35,InChI=1S/C16H10F4N2O2/c17-13-8-10(9-23-11-4-2-...
817,CHEMBL213934,CC(C)(C)OC(=O)N[C@@H](CCCCCS)C(=O)NC1CCCC1,4.36,"InChI=1S/C17H32N2O3S/c1-17(2,3)22-16(21)19-14(..."
2665,CHEMBL3274303,Ic1ccccn1,4.38,InChI=1S/C5H4IN/c6-5-3-1-2-4-7-5/h1-4H
2546,CHEMBL5218693,CCC(=O)CCCCC[C@H](NC(=O)[C@H]1CC12CCN(CC)CC2)c...,4.41,InChI=1S/C33H44N4O4/c1-5-24(38)10-8-7-9-11-27(...
462,CHEMBL2147944,CC(=O)N[C@@H](Cc1ccc(OCc2ccccc2)cc1)C(=O)O,4.43,InChI=1S/C18H19NO4/c1-13(20)19-17(18(21)22)11-...
617,CHEMBL272980,Nc1ccccc1NC(=O)c1ccc(CNc2nccc(-c3cccnc3)n2)cc1,4.46,InChI=1S/C23H20N6O/c24-19-5-1-2-6-21(19)28-22(...
1481,CHEMBL4218901,CC(C)[C@H](NS(=O)(=O)c1cccc(C(=O)NO)c1)C(=O)Nc...,4.47,InChI=1S/C18H21N3O5S/c1-12(2)16(18(23)19-14-8-...
2822,CHEMBL5396543,Nc1ccccc1NC(=O)/C=C/c1ccc(NC(=O)Cc2ccccc2)cn1,4.50,InChI=1S/C22H20N4O2/c23-19-8-4-5-9-20(19)26-21...
2708,CHEMBL5432418,Cn1cc(I)[n+](C)c1,4.51,"InChI=1S/C5H8IN2/c1-7-3-5(6)8(2)4-7/h3-4H,1-2H..."
1735,CHEMBL4552915,S=C1Sc2c(Cl)cccc2C2=NCCCN12,4.52,InChI=1S/C11H9ClN2S2/c12-8-4-1-3-7-9(8)16-11(1...
1322,CHEMBL4082254,C[C@@H](OCc1ccccc1)[C@@H]1N=C(c2ccccc2)c2ccccc...,4.53,InChI=1S/C29H31N3O4/c1-21(36-20-22-12-4-2-5-13...

In [57]:
data_work=data.drop(data.loc[::5].index)

In [58]:
data.head(30)

,molecule_chembl_id,canonical_smiles,pchembl_value_mean,inchi
2835,CHEMBL5429446,Nc1ccccc1NC(=O)c1ccc(NC(=O)Cc2cccc3ccccc23)cn1,4.01,InChI=1S/C24H20N4O2/c25-20-10-3-4-11-21(20)28-...
325,CHEMBL1767046,CNC(=O)/C(CCCCC[C@H](NCc1ccc(OC)cc1)C(=O)Nc1cc...,4.02,InChI=1S/C24H32N4O4/c1-25-23(29)22(28-31)12-8-...
316,CHEMBL1469,O=C(O)CCCc1ccccc1,4.03,InChI=1S/C10H12O2/c11-10(12)8-4-7-9-5-2-1-3-6-...
908,CHEMBL3605493,Nc1ccccc1NC(=O)c1ccc(CSC2=N[C@@H](Cc3ccccc3)CO...,4.06,InChI=1S/C24H23N3O2S/c25-21-8-4-5-9-22(21)27-2...
906,CHEMBL3605494,Nc1ccccc1NC(=O)c1ccc(CNC2=N[C@@H](c3ccccc3)CO2...,4.06,InChI=1S/C23H22N4O2/c24-19-8-4-5-9-20(19)26-22...
326,CHEMBL1767047,CNC(=O)/C(CCCCC[C@@H](C(=O)Nc1ccccc1)N(Cc1cccc...,4.06,InChI=1S/C30H36N4O3/c1-31-29(35)27(33-37)20-12...
914,CHEMBL3605499,Nc1ccccc1NC(=O)c1ccc(CNC2=N[C@@H](c3ccc(O)cc3)...,4.08,InChI=1S/C23H22N4O3/c24-19-3-1-2-4-20(19)26-22...
461,CHEMBL2148015,Cc1ccc(S(=O)(=O)N[C@@H](Cc2ccc(OCCc3ccccc3)cc2...,4.08,InChI=1S/C24H26N2O5S/c1-18-7-13-22(14-8-18)32(...
913,CHEMBL3605498,Nc1ccccc1NC(=O)c1ccc(CNC2=NC(c3ccc(C(F)(F)F)cc...,4.09,"InChI=1S/C24H21F3N4O2/c25-24(26,27)18-11-9-16(..."
905,CHEMBL3605495,Nc1ccccc1NC(=O)c1ccc(CNC2=N[C@H](c3ccccc3)CO2)cc1,4.09,InChI=1S/C23H22N4O2/c24-19-8-4-5-9-20(19)26-22...
2832,CHEMBL5419832,Nc1ccccc1NC(=O)c1ccc(NC(=O)Cc2ccccc2)cn1,4.11,InChI=1S/C20H18N4O2/c21-16-8-4-5-9-17(16)24-20...
2825,CHEMBL5414244,Nc1ccccc1NC(=O)/C=C/c1ccc(NC(=O)Cc2ccc3ccccc3c...,4.11,InChI=1S/C26H22N4O2/c27-23-7-3-4-8-24(23)30-25...
324,CHEMBL1767038,CNC(=O)/C(CCCCCCC(=O)Nc1cccc(-c2cccnc2)c1)=N\O,4.12,InChI=1S/C21H26N4O3/c1-22-21(27)19(25-28)11-4-...
2834,CHEMBL5399910,CC(C)C(C(=O)Nc1ccc(C(=O)Nc2ccccc2N)nc1)c1ccccc1,4.12,InChI=1S/C23H24N4O2/c1-15(2)21(16-8-4-3-5-9-16...
1530,CHEMBL4173739,Nc1ccccc1NC(=O)CCCc1ccc(N(CCCl)CCCl)cc1,4.12,InChI=1S/C20H25Cl2N3O/c21-12-14-25(15-13-22)17...
139,CHEMBL564916,Nc1ccccc1NC(=O)CCCCCC(c1c[nH]c2ccccc12)c1c[nH]...,4.13,InChI=1S/C29H30N4O/c30-25-13-6-9-16-28(25)33-2...
2901,CHEMBL5571764,CN(C(=O)c1ccc(-c2noc(C(F)(F)F)n2)cc1)c1ccccc1,4.14,InChI=1S/C17H12F3N3O2/c1-23(13-5-3-2-4-6-13)15...
481,CHEMBL2170173,COc1cc(COc2ccc(NC(=O)CCCCCCC(=O)OCCN=[N+]=[N-]...,4.17,InChI=1S/C24H29N7O5/c1-34-22-15-18(14-20(16-22...
2833,CHEMBL5433683,CCC(C(=O)Nc1ccc(C(=O)Nc2ccccc2N)nc1)c1ccccc1,4.18,InChI=1S/C22H22N4O2/c1-2-17(15-8-4-3-5-9-15)21...
321,CHEMBL1767030,CNC(=O)/C(CCCCCCC(=O)Nc1ccc2ccccc2c1)=N\O,4.19,InChI=1S/C20H25N3O3/c1-21-20(25)18(23-26)10-4-...
910,CHEMBL3605501,Nc1ccccc1NC(=O)c1ccc(CNC2=N[C@@H](Cc3ccccc3)CO...,4.20,InChI=1S/C24H24N4O2/c25-21-8-4-5-9-22(21)28-23...
1094,CHEMBL3771210,O=C(NO)c1csc(-c2cnccn2)n1,4.21,InChI=1S/C8H6N4O2S/c13-7(12-14)6-4-15-8(11-6)5...
322,CHEMBL1767032,CNC(=O)/C(CCCCCCC(=O)NC1c2ccccc2-c2ccccc21)=N\O,4.23,InChI=1S/C23H27N3O3/c1-24-23(28)20(26-29)14-4-...
482,CHEMBL2170172,Cc1cc(C)cc(COc2ccc(NC(=O)CCCCCCC(=O)OC(C)(C)C)...,4.27,InChI=1S/C27H37NO4/c1-20-16-21(2)18-22(17-20)1...
38,CHEMBL396097,O=C(NO)C(c1ccccc1)c1ccccc1,4.27,InChI=1S/C14H13NO2/c16-14(15-17)13(11-7-3-1-4-...
915,CHEMBL3605504,Nc1ccccc1NC(=O)c1ccc(CNC2=NC(c3ccccc3)(c3ccccc...,4.27,InChI=1S/C29H26N4O2/c30-25-13-7-8-14-26(25)32-...
2618,CHEMBL5269393,O=C(CCCCCCNC(=O)C(O)(O)C(F)(F)F)Nc1ccc(Cl)cc1,4.28,InChI=1S/C16H20ClF3N2O4/c17-11-6-8-12(9-7-11)2...
912,CHEMBL3605497,Nc1ccccc1NC(=O)c1ccc(CNC2=NC(c3cccc(F)c3)CO2)cc1,4.28,InChI=1S/C23H21FN4O2/c24-18-5-3-4-17(12-18)21-...
469,CHEMBL2148012,Cc1ccc(C(=O)N[C@@H](Cc2ccc(OCCc3ccccc3)cc2)C(=...,4.28,InChI=1S/C25H26N2O4/c1-18-7-11-21(12-8-18)24(2...
514,CHEMBL539664,Cn1cc(C=O)cc1CCC(=O)NO,4.28,InChI=1S/C9H12N2O3/c1-11-5-7(6-12)4-8(11)2-3-9...

In [59]:
data_work.head(25)

,molecule_chembl_id,canonical_smiles,pchembl_value_mean,inchi
325,CHEMBL1767046,CNC(=O)/C(CCCCC[C@H](NCc1ccc(OC)cc1)C(=O)Nc1cc...,4.02,InChI=1S/C24H32N4O4/c1-25-23(29)22(28-31)12-8-...
316,CHEMBL1469,O=C(O)CCCc1ccccc1,4.03,InChI=1S/C10H12O2/c11-10(12)8-4-7-9-5-2-1-3-6-...
908,CHEMBL3605493,Nc1ccccc1NC(=O)c1ccc(CSC2=N[C@@H](Cc3ccccc3)CO...,4.06,InChI=1S/C24H23N3O2S/c25-21-8-4-5-9-22(21)27-2...
906,CHEMBL3605494,Nc1ccccc1NC(=O)c1ccc(CNC2=N[C@@H](c3ccccc3)CO2...,4.06,InChI=1S/C23H22N4O2/c24-19-8-4-5-9-20(19)26-22...
914,CHEMBL3605499,Nc1ccccc1NC(=O)c1ccc(CNC2=N[C@@H](c3ccc(O)cc3)...,4.08,InChI=1S/C23H22N4O3/c24-19-3-1-2-4-20(19)26-22...
461,CHEMBL2148015,Cc1ccc(S(=O)(=O)N[C@@H](Cc2ccc(OCCc3ccccc3)cc2...,4.08,InChI=1S/C24H26N2O5S/c1-18-7-13-22(14-8-18)32(...
913,CHEMBL3605498,Nc1ccccc1NC(=O)c1ccc(CNC2=NC(c3ccc(C(F)(F)F)cc...,4.09,"InChI=1S/C24H21F3N4O2/c25-24(26,27)18-11-9-16(..."
905,CHEMBL3605495,Nc1ccccc1NC(=O)c1ccc(CNC2=N[C@H](c3ccccc3)CO2)cc1,4.09,InChI=1S/C23H22N4O2/c24-19-8-4-5-9-20(19)26-22...
2825,CHEMBL5414244,Nc1ccccc1NC(=O)/C=C/c1ccc(NC(=O)Cc2ccc3ccccc3c...,4.11,InChI=1S/C26H22N4O2/c27-23-7-3-4-8-24(23)30-25...
324,CHEMBL1767038,CNC(=O)/C(CCCCCCC(=O)Nc1cccc(-c2cccnc2)c1)=N\O,4.12,InChI=1S/C21H26N4O3/c1-22-21(27)19(25-28)11-4-...
2834,CHEMBL5399910,CC(C)C(C(=O)Nc1ccc(C(=O)Nc2ccccc2N)nc1)c1ccccc1,4.12,InChI=1S/C23H24N4O2/c1-15(2)21(16-8-4-3-5-9-16...
1530,CHEMBL4173739,Nc1ccccc1NC(=O)CCCc1ccc(N(CCCl)CCCl)cc1,4.12,InChI=1S/C20H25Cl2N3O/c21-12-14-25(15-13-22)17...
2901,CHEMBL5571764,CN(C(=O)c1ccc(-c2noc(C(F)(F)F)n2)cc1)c1ccccc1,4.14,InChI=1S/C17H12F3N3O2/c1-23(13-5-3-2-4-6-13)15...
481,CHEMBL2170173,COc1cc(COc2ccc(NC(=O)CCCCCCC(=O)OCCN=[N+]=[N-]...,4.17,InChI=1S/C24H29N7O5/c1-34-22-15-18(14-20(16-22...
2833,CHEMBL5433683,CCC(C(=O)Nc1ccc(C(=O)Nc2ccccc2N)nc1)c1ccccc1,4.18,InChI=1S/C22H22N4O2/c1-2-17(15-8-4-3-5-9-15)21...
321,CHEMBL1767030,CNC(=O)/C(CCCCCCC(=O)Nc1ccc2ccccc2c1)=N\O,4.19,InChI=1S/C20H25N3O3/c1-21-20(25)18(23-26)10-4-...
1094,CHEMBL3771210,O=C(NO)c1csc(-c2cnccn2)n1,4.21,InChI=1S/C8H6N4O2S/c13-7(12-14)6-4-15-8(11-6)5...
322,CHEMBL1767032,CNC(=O)/C(CCCCCCC(=O)NC1c2ccccc2-c2ccccc21)=N\O,4.23,InChI=1S/C23H27N3O3/c1-24-23(28)20(26-29)14-4-...
482,CHEMBL2170172,Cc1cc(C)cc(COc2ccc(NC(=O)CCCCCCC(=O)OC(C)(C)C)...,4.27,InChI=1S/C27H37NO4/c1-20-16-21(2)18-22(17-20)1...
38,CHEMBL396097,O=C(NO)C(c1ccccc1)c1ccccc1,4.27,InChI=1S/C14H13NO2/c16-14(15-17)13(11-7-3-1-4-...
2618,CHEMBL5269393,O=C(CCCCCCNC(=O)C(O)(O)C(F)(F)F)Nc1ccc(Cl)cc1,4.28,InChI=1S/C16H20ClF3N2O4/c17-11-6-8-12(9-7-11)2...
912,CHEMBL3605497,Nc1ccccc1NC(=O)c1ccc(CNC2=NC(c3cccc(F)c3)CO2)cc1,4.28,InChI=1S/C23H21FN4O2/c24-18-5-3-4-17(12-18)21-...
469,CHEMBL2148012,Cc1ccc(C(=O)N[C@@H](Cc2ccc(OCCc3ccccc3)cc2)C(=...,4.28,InChI=1S/C25H26N2O4/c1-18-7-11-21(12-8-18)24(2...
514,CHEMBL539664,Cn1cc(C=O)cc1CCC(=O)NO,4.28,InChI=1S/C9H12N2O3/c1-11-5-7(6-12)4-8(11)2-3-9...
1107,CHEMBL3769415,COc1ccc(-c2nc(C(=O)NO)co2)cc1,4.29,InChI=1S/C11H10N2O4/c1-16-8-4-2-7(3-5-8)11-12-...

# Creating sdf files

Creating test set

In [60]:
PandasTools.AddMoleculeColumnToFrame(data_test, 'canonical_smiles', 'Molecule')

C:\Users\ovtti\anaconda3\Lib\site-packages\rdkit\Chem\PandasTools.py:380: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame[molCol] = frame[smilesCol].map(Chem.MolFromSmiles)

In [61]:
HTML(data_test.head().to_html())

In [62]:
PandasTools.WriteSDF(data_test, 'HDAC8_test.sdf', molColName='Molecule', properties=list(data.columns))

Creating work set

In [63]:
PandasTools.AddMoleculeColumnToFrame(data_work, 'canonical_smiles', 'Molecule')

In [64]:
HTML(data_work.head().to_html())

In [65]:
PandasTools.WriteSDF(data_work, 'HDAC8_work.sdf', molColName='Molecule', properties=list(data.columns))